---
- name: Set controller_login fact
  ansible.builtin.set_fact:
    controller_login: &controller_login
      controller_username: admin
      controller_password: "{{ admin_password }}"
      controller_host: https://{{ ansible_host }}:8443
      validate_certs: false
  no_log: true

- name: Debug run_commands_user
  ansible.builtin.debug:
    msg: "run_commands_user: {{ run_commands_user }}"

- name: Check normal user
  ansible.builtin.debug:
    msg: "{{ ansible_user_id }}"

- name: Run whoami command
  become: true
  become_user: "{{ run_commands_user }}"
  changed_when: false
  ansible.builtin.command:
    cmd: "whoami"
  register: whoami

- name: Debug the whoami user
  ansible.builtin.debug:
    msg: "{{ whoami }}"

- name: Make sure Automation Controller is online before changing base URL
  become: true
  become_user: "{{ run_commands_user }}"
  containers.podman.podman_container:
    name: automation-controller-web
    state: started
  register: controller_online
  until: controller_online is not failed
  retries: 5

- name: Set password
  block:
    - name: Change admin password R3dh4t1!
      awx.awx.user:
        username: "admin"
        password: "{{ admin_password }}"
        state: present
        superuser: true
        <<: *controller_login
      register: set_password
      until: set_password is not failed
  rescue:
    - name: Change admin password
      awx.awx.user:
        username: "admin"
        password: "{{ admin_password }}"
        state: present
        superuser: true
        <<: *controller_login
      register: set_password
      until: set_password is not failed
