---
- name: aap setup for control node # TODO put back
  include_tasks: 10_aap_setup.yml
  tags:
    - aap_setup

# Port 8443 used in containerized installs
- name: Check to see if automation controller is already up and running
  ansible.builtin.uri:
    url: https://localhost:8443/api/v2/ping/
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: check_controller
  ignore_errors: true
  failed_when: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool

- name: Install controller if knob is set
  ansible.builtin.include_tasks: "12_controller.yml"
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    # - check_controller.status != 200 # TODO put back

- name: Install packages
  ansible.builtin.include_tasks: 15_package_dependencies.yml

- name: Common workshop setup for control node
  ansible.builtin.include_tasks: 20_all_workshop.yml


